# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-05-19 22:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pic', '0002_auto_20200520_0117'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='description',
            field=models.TextField(),
        ),
    ]
