# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-05-24 14:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pic', '0002_image_place'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='place',
            new_name='location',
        ),
        migrations.RenameField(
            model_name='location',
            old_name='place',
            new_name='location',
        ),
    ]
