# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-05-24 14:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pic', '0003_auto_20200524_1747'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='location',
            new_name='place',
        ),
        migrations.RenameField(
            model_name='location',
            old_name='location',
            new_name='place',
        ),
    ]
