# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-05-24 15:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pic', '0005_auto_20200524_1844'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='category',
            field=models.CharField(blank=True, choices=[('TRAVEL', 'TRAVEL'), ('PERSONAL', 'PERSONAL'), ('HOBBY', 'HOBBY'), ('PHOTO', 'PHOTO')], max_length=30),
        ),
    ]
